-- Create signals table for storing trading signals
CREATE TABLE IF NOT EXISTS signals (
    id SERIAL PRIMARY KEY,
    market_id VARCHAR(255) NOT NULL,
    signal VARCHAR(10) NOT NULL, -- 'BUY', 'SELL', 'WATCH'
    score INTEGER NOT NULL, -- 0-100
    reason TEXT,
    raw JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_signals_market_id ON signals(market_id);
CREATE INDEX IF NOT EXISTS idx_signals_signal ON signals(signal);
CREATE INDEX IF NOT EXISTS idx_signals_created_at ON signals(created_at);

COMMENT ON TABLE signals IS 'Trading signals generated by rule-based signal engine';
COMMENT ON COLUMN signals.market_id IS 'Market ID';
COMMENT ON COLUMN signals.signal IS 'Signal type: BUY, SELL, WATCH';
COMMENT ON COLUMN signals.score IS 'Signal score 0-100';
COMMENT ON COLUMN signals.reason IS 'Human-readable reason for the signal';
COMMENT ON COLUMN signals.raw IS 'Raw signal data including all metrics';
